name: task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  responsive_framework: ^1.0.0
  freezed_annotation: ^2.2.0
  connectivity_plus: ^3.0.6
  either_dart: ^0.3.0
  go_router:  ^7.0.0
  equatable: ^2.0.5
  riverpod: ^2.3.6
  hooks_riverpod:
  http: ^0.13.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed:
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  assets:
    - assets/images/
    - assets/lang/
    - assets/icons/
    - assets/fonts/

  uses-material-design: true

